### ISSUE TITLE
운영체제 02번 pdf까지 정리

### ISSUE THREAD

**Issue by flowjiyun** [42NoGun/dev-blog#1]
첫주 가볍게 운영체제 개요 부분 정리해 봅시다.
깃헙 블로그에 올릴 수 있도록 md file로 정리해서  pull request 올려주세요.

**Comment by ji-junhyuk** [comment]
지윤님 정리한거 개인 블로그에 올리고, 링크만 공유하는 식도 괜찮을까요?

**Comment by flowjiyun** [comment]
아 그렇게 해도 상관없을 거 같아용!!
